name: Run pytest for slow tests

on: [push]

jobs:
  build:

    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ${{ matrix.os-python.image }}
    strategy:
      max-parallel: 4
      matrix:
        os-python:
          - image: ubuntu-latest
            python-version: '3.11'

        numpy-version: ['numpy~=2.1.0']

        # incompatible with scipy>=1.15.0 because of the pickled elements
        scipy-version: ['scipy~=1.13.0']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.os-python.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.os-python.python-version }}
        cache: 'pip' # caching pip dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt "${{ matrix.numpy-version }}" "${{ matrix.scipy-version }}"
        pip list

    - name: Install package
      run: |
        pip install .

    - name: Lint with flake8
      run: |
        pip install flake8
        
        # stop the build if there are Python syntax errors 
        # or undefined names
        flake8 \
          --count \
          --exclude .git,build,__pycache__ \
          --select=E9,F63,F7,F82 \
          --show-source \
          --statistics \
          .
        
        # exit-zero treats all errors as warnings. 
        # The GitHub editor is 127 chars wide
        flake8 \
          --count \
          --exclude .git,build,__pycache__ \
          --exit-zero \
          --max-complexity=10 \
          --max-line-length=127 \
          --statistics \
          .

    - name: Test with pytest
      run: |
        pip install pytest
        pytest -vv -m slow
